Milestone: Mobile menu
davmba/My-Portfolio-DaveMba pull request #11
Opened 2022-07-25 15:24 UTC by davmba

**### Mobile menu milestone: Portfolio**
**In this milestone, we:**

- Implement the mobile menu using the recently acquired JavaScript knowledge.

2022-07-25 15:48 UTC, topeogunleye reviewed
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that involves JavaScript but doesn't have JavaScript linters set up.  I kindly suggest that you add [html-css-js](https://github.com/microverseinc/linters-config/tree/master/html-css-js) linters to your project and ensure all your linters including ESLint are green.

## ESLint AutoFix
- if you have a lot of JavaScript line errors, I kindly suggest you fix them by running `npx eslint . --fix`, but please get used to fixing the errors line by line also because it'll help you learn best practices.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-07-25 23:50 UTC, mirouhml requested changes
# REQUIRED CHANGES 🔴

Hi @davmba, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media4.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif?cid=ecf05e47n6s5huda7qh40syoppcaspe9vx68ddmxerd08owm&rid=giphy.gif&ct=g)

## Highlights

- Great job setting up the correct linters ✔️
- Highly organized and clean code ✔️ 👨🏻‍💻
- Professional documentation ✔️
- Correct workflow ✔️
- Meaningful commit messages ✔️

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-25 23:50 UTC, mirouhml commented on index.html
>          </div>
- [ ] Please know that the mobile menu should cover all of the screen, kindly fix this:

![image](https://user-images.githubusercontent.com/20567503/180893076-537c9830-9473-4d0e-84f0-939c46cc7a31.png)

2022-07-25 23:50 UTC, mirouhml commented on index.html
> +              <li><a href="#portfolio" class="nav-link">Portfolio</a></li>
- [ ] Please know that the portfolio link should take the user to the `recent works` sections, kindly fix this. 😁

2022-07-26 00:32 UTC, Reem-lab approved these changes
# Hi Team, 👋🏻👋🏻👋🏻 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🔥🔥🔥🎉🎉
<img src="https://media1.giphy.com/media/G7lfJRrvdhtxK8OVGy/giphy.gif"/>

## Highlights ✨✨
- No Linters error ✅✅
- Great job on working on the requested changes ✅✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-26 00:51 UTC, merged